[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "zisi" # Changed to zisi for standard Netlify build

# --- PROXY REDIRECT RULES ---
# These map clean API calls to the actual Netlify function paths.
# They are essential for the front-end login to work.

# 1. User Data Fetch (GET/Firebase Authentication)
[[redirects]]
  from = "/api/user-data"
  to = "/.netlify/functions/fetch-user-data"
  status = 200

# 2. Generate Verification Code (POST)
[[redirects]]
  from = "/api/generate-code"
  to = "/.netlify/functions/generate-verification-code"
  status = 200

# 3. Verify Account (POST)
[[redirects]]
  from = "/api/verify-user"
  to = "/.netlify/functions/verify-roblox-user"
  status = 200
